patternfly/chatbot

- packages/module/src/VirtualAssistant/VirtualAssistant.test.tsx
- packages/module/src/VirtualAssistant/VirtualAssistant.tsx
We were missing this functionality in the extension, basically being able to press Enter key to send a message.
I was thinking whether we should pass the keypress handler and do it from our virtual assistant or in the extension.
Since this is a similar functionality as other chat clients, it makes sense to have it here directly.
I didn't add any way to override, but if we feel that this is a need in the future we could accept the keypress handler.
- Allow to send the messages when pressing enter key
- Behaves like it does on chat clients, pressing shift + enter will jump to the next line instead of sending the message
- Adding tests
> Handle key press of the input

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/AttachmentEdit/AttachmentEdit.md
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/AttachmentEdit/AttachmentEdit.tsx
- packages/module/src/AttachmentEdit/AttachmentEdit.scss
- packages/module/src/AttachmentEdit/AttachmentEdit.tsx
- packages/module/src/AttachmentEdit/index.ts
- packages/module/src/index.ts
- packages/module/src/main.scss
I'm building this with the current version of the modal for the time being given that the rest of the assistant layout doesn't seem to be built yet. This means that the footer is slightly different, as is the title and footer spacing, title styling, background color, etc. I am also using the current PF6 code editor, which looks different. If this winds up being the ultimate design, we can go back and customize this to match more closely once decisions have been made.
| Original | Less Gorgeous with Standard PatternFly 6 |
| -------- | ------- |
| <img width="312" alt="Screenshot 2024-08-20 at 9 09 57 AM" src="https://github.com/user-attachments/assets/b342cd43-9ec7-4116-9d03-e04c31554d52">| <img width="312" alt="Screenshot 2024-08-20 at 9 32 46 AM" …
> feat(AttachmentEdit): Add AttachmentEdit

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/PreviewAttachment/PreviewAttachment.md
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/PreviewAttachment/PreviewAttachment.tsx
- packages/module/src/AttachmentEdit/AttachmentEdit.tsx
- packages/module/src/CodeModal/CodeModal.scss
- packages/module/src/CodeModal/CodeModal.tsx
- packages/module/src/CodeModal/index.ts
- packages/module/src/PreviewAttachment/PreviewAttachment.tsx
- packages/module/src/PreviewAttachment/index.ts
- packages/module/src/index.ts
- packages/module/src/main.scss
Will be easier to review after https://github.com/patternfly/virtual-assistant/pull/82 merges since it modifies the commit there.
Turned EditAttachment into a reusable CodeModal component so I could use the same base component for both EditAttachment and PreviewAttachment. Added limited customization required for PreviewAttachment. The same disclaimers apply for PreviewAttachment for the design - I am using the standard code editor and modal with no adjustments since we have a need for speed. We'll go back and modify as needed once designs are final.
Fixes https://github.com/patternfly/virtual-assistant/issues/58.
> feat(PreviewAttachment): add Preview Attachment component 

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/FileDropZone/FileDropZone.md
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/FileDropZone/FileDropZone.tsx
- packages/module/src/FileDropZone/FileDropZone.tsx
- packages/module/src/FileDropZone/index.ts
- packages/module/src/index.ts
Again, this deviates from the design significantly because the design isn't based on PatternFly 6. We are using PatternFly components where available for speedy development purposes. The only real big change here from the PatternFly demo is that the drop zone is hidden until engaged, and that we're not showing the status indicators. The design did not seem to include any handling here explicitly beyond what a successful upload looks like (outside of the scope of this component). We probably need a way to indicate a failure in a similar location.
Fixes https://github.com/patternfly/virtual-assistant/issues/59.
> feat(FileDropZone): Add drop zone for file upload purposes

- packages/module/src/CodeModal/CodeModal.scss
- packages/module/src/CodeModal/CodeModal.tsx
- packages/module/src/PreviewAttachment/PreviewAttachment.tsx
- packages/module/src/main.scss
A decision was made to stick to the original design rather than PF6, so I'm attempting to match here. One exception is the copy to clipboard icon - PF does not easily let me swap this, and forking it is more involved/code-heavy. We can file an issue and address this as a follow-on. The dark modal background also seems a little too dark in context, and I'm having a tough time changing the margins on the Monaco editor in the limited time I want to spend on this. It's third-party with a lot of absolute positioning. It might be better to put a pin in those for now and file issues so we can circle back after code freeze. I would rather work on finishing out the feature so we have something to ship.
Design specs:
* https://www.figma.com/design/YV8fXr4jjEjUqhvRzI0tT2/PF-Extension%3A-Chatbot?t=dwz …
> fix(CodeModal): Restyle to match updated design

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/FileDropZone/FileDropZone.tsx
- packages/module/src/FileDropZone/FileDropZone.scss
- packages/module/src/FileDropZone/FileDropZone.tsx
- packages/module/src/main.scss
A decision was made to follow the design more closely - this applies custom style overrides on top of PF6.
Design spec: https://www.figma.com/design/YV8fXr4jjEjUqhvRzI0tT2/PatternFly%3A-Chatbot-Design-Framework?node-id=404-17145&t=RP6bjDiAIAIRYhM0-4
> fix(FileDropZone): restyle FileDropZone to match design

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/AttachmentError/AttachmentError.md
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/AttachmentError/AttachmentError.tsx
We can just use the default alert for this, hurray! But here is a sample of how to use it, that you can copy and paste.
Fixes https://github.com/patternfly/virtual-assistant/issues/90.
> chore(AttachmentError): Add demo for AttachmentError

- package-lock.json
- package.json
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/ChatbotAttachment/ChatbotAttachment.tsx
- packages/module/src/MessageBar/AttachButton.tsx
- packages/module/src/MessageBar/MessageBar.scss
- packages/module/src/MessageBar/MessageBar.tsx
Used react-dropzone to hook up the attach button, and flowed it into the attachment demo.
Needs to merge after https://github.com/patternfly/virtual-assistant/pull/98 since it's based on that.
Fixes https://github.com/patternfly/virtual-assistant/issues/100.
> feat(ChatbotAttachment): Hook up attach button

- packages/module/src/Message/TextMessage/TextMessage.scss
If you placed .pf-v6-c-content inside of the blue user text box, .pf-v6-c-content text styles would override the blue user text box styles. This could cause black text inside of the blue box instead of white text.
Michael Coker suggested a more broad approach here if we want to go back to that in the future: https://patternfly.slack.com/archives/C03LQ25DDLN/p1726153079441679?thread_ts=1726148417.697719&cid=C03LQ25DDLN. It sounds like we should go narrow so we don't interfere with other PatternFly components we may pull in as we add more message subtypes. 
This should hopefully make everything white. I pulled in some samples from Michael Coker here: https://codepen.io/mcoker/pen/abgxBOa?editors=1100 into the Message component and went through them to make sure they looked ok. I added …
> fix(TextMessage): Always override text color in user message bubbles

- packages/module/src/ChatbotHeader/ChatbotHeader.scss
The logo was moving whenever you selected an item in the model dropdown. This makes it so that nothing but the dropdown moves.
Fixes https://github.com/patternfly/virtual-assistant/issues/110.
> fix(ChatbotHeader): Adjust styles so logo doesn't move

- packages/module/src/ChatbotWelcomePrompt/ChatbotWelcomePrompt.scss
- packages/module/src/ChatbotWelcomePrompt/ChatbotWelcomePrompt.tsx
Rohit's last PR had the sample prompts side by side full screen. It looks like we lost this in the first CSS refactor. I am restoring that functionality. Rohit's PR was https://github.com/patternfly/virtual-assistant/pull/94. I used it as a point of comparison for the behavior of the welcome prompts.
Fixes https://github.com/patternfly/virtual-assistant/issues/136
> fix(ChatbotWelcomePrompt): Sample prompts should be a row on fullscreen

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/AttachmentDemos.md
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/ChatbotAttachment.tsx
- packages/module/src/AttachmentEdit/AttachmentEdit.tsx
- packages/module/src/Chatbot/Chatbot.scss
- packages/module/src/CodeModal/CodeModal.scss
- packages/module/src/CodeModal/CodeModal.tsx
- packages/module/src/FileDropZone/FileDropZone.scss
- packages/module/src/FileDropZone/FileDropZone.tsx
- packages/module/src/MessageBar/MessageBar.scss
- packages/module/src/MessageBox/JumpButton.scss
- packages/module/src/PreviewAttachment/PreviewAttachment.tsx
Working on integrating display mode feature into FileDropZone/CodeModal so we can add the header into the attachment demos. This does not include really include many design updates. The purpose is mostly just to integrate display mode and update the modal behavior so it makes sense.
Will fix https://github.com/patternfly/virtual-assistant/issues/128 eventually.
> fix(FileDropZone/CodeModal): Pass Chatbot display mode down

- packages/module/src/FileDetailsLabel/FileDetailsLabel.scss
- packages/module/src/FileDetailsLabel/FileDetailsLabel.tsx
Kayla and Lucia met and decided on a different approach to FileDetailsLabel - updating that here.
|Before|After|
|-|-|
|<img width="215" alt="Screenshot 2024-09-19 at 2 04 50 PM" src="https://github.com/user-attachments/assets/3f51927d-f1d4-4588-a5e9-a547147372be">|<img width="234" alt="Screenshot 2024-09-19 at 2 03 03 PM" src="https://github.com/user-attachments/assets/c7733f2a-6f8a-427b-a811-e4c6270a8370">
|<img width="200" alt="Screenshot 2024-09-19 at 2 04 56 PM" src="https://github.com/user-attachments/assets/262f206d-4a66-4e89-8a49-d54e6324c49d">|<img width="215" alt="Screenshot 2024-09-19 at 2 03 12 PM" src="https://github.com/user-attachments/assets/f2587974-ea21-49dd-b508-ce001e628d90">
> fix(FileDetailsLabel): Kayla wants to change the background

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/Chatbot/Chatbot.tsx
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/ChatbotAttachment.tsx
Mark's original design called for us to show which display mode was selected in the dropdown. This was reproduced in Kayla's work. This brings us up to parity with both. Kayla wants to continue using a default PF dropdown for now.
> chore(Chatbot/ChatbotAttachment): Show selected state on display mode dropdowns

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/Chatbot/Chatbot.md
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/ChatbotHeader/ChatbotHeader.md
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/ChatbotHeader/PF-IconLogo-Color.svg
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/ChatbotHeader/PF-IconLogo-Reverse.svg
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/AttachmentDemos.md
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/Chatbot.md
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/Chatbot.tsx
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/ChatbotAttachment.tsx
- packages/module/src/ChatbotHeader/ChatbotHeader.scss
Kayla wants a smaller logo on smaller chatbot sizes - updating CSS and demos to reflect this.
|State|Light mode|Dark mode|
|-|-|-|
|Overlay|<img width="506" alt="Screenshot 2024-09-19 at 3 16 41 PM" src="https://github.com/user-attachments/assets/3bbd2ff9-7b89-488a-af66-afbc3ef2431a">|<img width="488" alt="Screenshot 2024-09-19 at 3 17 03 PM" src="https://github.com/user-attachments/assets/abd8e0f7-f12d-497d-8996-c4c1650e5af9">
|Docked|<img width="200" alt="Screenshot 2024-09-19 at 3 17 35 PM" src="https://github.com/user-attachments/assets/d9a57931-809b-4339-9f79-e5896b468a75">|<img width="200" alt="Screenshot 2024-09-19 at 3 17 10 PM" src="https://github.com/user-attachments/assets/e986f52b-6a40-47ba-986e-1e9d5aa3289a">
|Full screen|<img width="250" alt="Screenshot 2024-09-19 at 3 17 …
> chore(ChatbotHeader): Update logos

- packages/module/src/ChatbotHeader/ChatbotHeaderOptionsDropdown.tsx
- packages/module/src/ChatbotHeader/ChatbotHeaderSelectorDropdown.tsx
onSelect doesn't trigger appropriately in RHDH Lightspeed and only RHDH Lightspeed. I'm wondering if this isn't the cause - I'm hoping to pull this in there and see if this fixes their problems.
> fix(ChatbotHeaderSelectorDropdown): Try to fix onSelect problem in RHDH

- packages/module/src/ChatbotContent/ChatbotContent.scss
This doesn't show in our workspace, but RHDH sees a double scrollbar on this component. Overflow: hidden fixed it in their workspace; hoping they can pull this in and see resolution.
> fix(ChatbotContent): Fix double scroll issue for RHDH

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/ChatbotAttachment/ChatbotAttachment.md
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/ChatbotFooter/ChatbotFooter.md
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/ChatbotFooter/ChatbotMessageBarAttach.tsx
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/ChatbotAttachmentMenu.tsx
- packages/module/src/MessageBar/AttachButton.tsx
Left out input required for react-dropzone to work in Safari and Firefox. Consumers should only have to worry about adding this if they incorporate upload into a dropdown, which we give them full control over.
I added a comment where applicable. Also updated a few docs.
> fix(AttachButton/AttachmentMenu): Add input

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/ChatbotHeader/ChatbotHeader.md
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/ChatbotHeader/ChatbotHeaderBasic.tsx
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/AttachmentDemos.md
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/Chatbot.md
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/Chatbot.tsx
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/ChatbotAttachment.tsx
- packages/module/src/Chatbot/Chatbot.scss
- packages/module/src/ChatbotContent/ChatbotContent.scss
- packages/module/src/ChatbotFooter/ChatbotFooter.scss
- packages/module/src/ChatbotHeader/ChatbotHeader.scss
- packages/module/src/ChatbotHeader/ChatbotHeader.tsx
- packages/module/src/ChatbotHeader/ChatbotHeaderActions.tsx
- packages/module/src/ChatbotHeader/ChatbotHeaderMain.tsx
- packages/module/src/ChatbotHeader/ChatbotHeaderMenu.tsx
- packages/module/src/ChatbotHeader/ChatbotHeaderSelectorDropdown.tsx
- packages/module/src/ChatbotHeader/ChatbotHeaderTitle.tsx
- packages/module/src/ChatbotHeader/index.ts
- packages/module/src/FileDropZone/FileDropZone.scss
- packages/module/src/MessageBox/MessageBox.scss
I refactored the header into something more composable - the old header started to have problems if you dropped the menu bar. I added an example that lets you turn things on and off so it's more clear how that works. Also added to the two full-page demos with a menu bar.
> fix(Header): Refactor into composable grid

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/Chatbot.tsx
- packages/module/src/MessageBar/MessageBar.tsx
Demos should allow for questions to be asked, and scroll to the bottom as messages are added. We have also decided to try and show the loading vs. non-loading states if it's not a heavy lift.
> chore(docs): Update demos to scroll when new questions are asked

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/Chatbot.tsx
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/ChatbotAttachment.tsx
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/ChatbotAttachmentMenu.tsx
- packages/module/src/Message/Message.scss
- packages/module/src/Message/Message.tsx
- packages/module/src/ResponseActions/ResponseActionButton.tsx
- packages/module/src/ResponseActions/ResponseActions.scss
- packages/module/src/ResponseActions/ResponseActions.tsx
- packages/module/src/ResponseActions/index.ts
- packages/module/src/index.ts
- packages/module/src/main.scss
Messages should have buttons for feedback and other actions. Users should be able to configure as many of these as they wish on a per message basis. This is a proof of concept.
Some questions I have at this stage:
To do:
> feat(ResponseActions): Add ResponseActions to Messages

- packages/module/src/Chatbot/Chatbot.scss
- packages/module/src/FileDropZone/FileDropZone.scss
We had baked in some assumptions with grid to get FileDropZone to work correctly. Unfortunately, this broke when the header was left out. I am switching us to a more flexible flex layout for Chatbot.
> fix(Chatbot/FileDropzone): Switch from grid to flex layout

- config/webpack.cy.config.js
- package-lock.json
- package.json
- packages/module/package.json
- packages/module/src/ChatbotContent/ChatbotContent.scss
- packages/module/src/CodeModal/CodeModal.tsx
- packages/module/src/FileDetails/FileDetails.tsx
- packages/module/src/Message/Message.tsx
I'm still seeing issues in Composer AI where I have to adjust webpack to handle path. I don't think we should assume customers can do this. This should hopefully fix it. I'm also adding an id to messages since it would be helpful in Composer AI.
> fix(docs): Switch from path to path-browserify and add id to Message

- packages/module/src/AttachMenu/AttachMenu.tsx
- packages/module/src/ChatbotConversationHistoryNav/ChatbotConversationHistoryNav.tsx
- packages/module/src/ChatbotHeader/ChatbotHeaderMenu.tsx
- packages/module/src/ChatbotHeader/ChatbotHeaderOptionsDropdown.tsx
- packages/module/src/ChatbotHeader/ChatbotHeaderSelectorDropdown.tsx
Allow user to customize user-composable components for i18n, etc.
I'm leaving the ones in the old code that it looks like we didn't write, as well as the CodeMessage, since the user can't touch that.
> fix(docs): Add prop for aria label

- packages/module/src/Chatbot/Chatbot.tsx
- packages/module/src/MessageBox/JumpButton.tsx
Users could tab through invisible jump links and chatbots - Eric notes that this is no good. This should remove them appropriately.
> fix(Chatbot/JumpButton): Remove content from DOM when not visible

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/Chatbot/Chatbot.md
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/Chatbot.md
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/Chatbot.tsx
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/EmbeddedChatbot.tsx
- packages/module/src/MessageBox/MessageBox.scss
- packages/module/src/MessageBox/MessageBox.tsx
Messages should be announced to assistive devices. I added a prop to MessageBox to allow for this and updated our two demos with message sending so they make announcements. I also documented this in the Chatbot container docs. I checked this worked with VoiceOver, but I can't speak to any other tools.
Taking this opportunity to also switch our scrolling method and add better ids.
> fix(MessageBox): Announce new messages

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/ChatbotConversationHistoryNav/ChatbotHeaderDrawer.tsx
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/ChatbotConversationHistoryNav/ChatbotHeaderDrawerInHeader.tsx
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/ChatbotConversationHistoryNav/ChatbotHeaderDrawerWithActions.tsx
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/Chatbot.tsx
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/EmbeddedChatbot.tsx
- packages/module/src/ChatbotConversationHistoryNav/ChatbotConversationHistoryNav.tsx
- packages/module/src/ChatbotHeader/ChatbotHeaderOptionsDropdown.tsx
- packages/module/src/ChatbotHeader/ChatbotHeaderSelectorDropdown.tsx
The drawer's focus trap requires a listener for the escape key. Because it wraps the children, they also wind up triggering the listener if they use the escape key (this affects the header dropdowns). I am passing in a separate prop for handling the escape key so it doesn't matter if they trigger, and turning off the trigger also for the menu items within the panel. Escape is also used for leaving dropdowns, and we have those present in the panel if actions are enabled.
> fix(ChatbotHeaderSelectorDropdown/ChatbotHeaderOptionsDropdown): Should be keyboard navigable

- packages/module/src/Message/Message.tsx
Eric notes that these avatars would be noise if the chat goes on a long time. This is a more decorative element. With this change, screenreaders won't mention the avatars.
> fix(Message): Switch to alt='' for avatars

- packages/module/src/ChatbotHeader/ChatbotHeaderSelectorDropdown.tsx
Set aria label to value and then updated on onSelect. Also exposed the tooltip content for user configuration while I was in there.
> fix(ChatbotHeaderSelectorDropdown): Aria label should include current value

- packages/module/src/AttachMenu/AttachMenu.tsx
Needed to change onOpenChangeKeys so it excluded tab - Eric absolutely called it.
> fix(AttachMenu): Allow tabbing into input

- packages/module/src/Message/Message.tsx
This makes it a little easier to navigate with screenreaders. This does make it show up in the landmarks menu, but I'm not sure if this is good enough. Do we need to make sure these work?: https://support.apple.com/guide/voiceover/read-text-vo2706/10/mac/15.0. VO + S works but you have to arrow through. If there's other improvements we need here, let me know.
> fix(Message): Make each Message a section

- packages/module/src/FileDetails/FileDetails.tsx
Need to add additional extensions to map for use in Composer AI. React-dropzone is filetype agnostic, so it shouldn't care, but this will allow us to display labels with intelligent file types.
> feat(FileDetails): Add additional file types

- packages/module/src/MessageBox/JumpButton.scss
- packages/module/src/MessageBox/JumpButton.tsx
- packages/module/src/main.scss
> fix(JumpButton): Shrink it for now

- packages/module/src/CodeModal/CodeModal.scss
- packages/module/src/CodeModal/CodeModal.tsx
- packages/module/src/main.scss
Backdrop CSS change was not scoped, leading to leaking in PatternFly.org. This should scope it appopriately.
> fix(CodeModal): Add scope to backdrop CSS

- packages/module/src/FileDetails/FileDetails.tsx
- packages/module/src/FileDetails/__snapshots__/FileDetails.test.tsx.snap
- packages/module/src/FileDetailsLabel/FileDetailsLabel.scss
- packages/module/src/FileDetailsLabel/FileDetailsLabel.tsx
- packages/module/src/FileDetailsLabel/__snapshots__/FileDetailsLabel.test.tsx.snap
We were relying on the default PatternFly label behavior for long titles. Mark raised a concern that this will cause problems in the future when we enable multiple file uploads. This PR adjusts the chip so it has text truncation and a max width. The loading state should also look a little more consistent when titles are long.
Modals use the same text treatment, meaning that they will have truncation.
Short title:
Long title:
> fix(FileDetails/FileDetailsLabel): Adjust chip width

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/ChatbotFooter/ChatbotFooter.md
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/ChatbotFooter/ChatbotMessageBarStop.tsx
- packages/module/src/MessageBar/AttachButton.tsx
- packages/module/src/MessageBar/MessageBar.scss
- packages/module/src/MessageBar/MessageBar.tsx
- packages/module/src/MessageBar/MicrophoneButton.tsx
- packages/module/src/MessageBar/SendButton.tsx
- packages/module/src/MessageBar/StopButton.scss
- packages/module/src/MessageBar/StopButton.tsx
This is a new feature requested by folks using streaming - click the button and wire it up so it can interrupt a streaming chatbot response.
> feat(StopButton): Add StopButton for MessageBar

- packages/module/src/Message/CodeBlockMessage/CodeBlockMessage.tsx
- packages/module/src/Message/Message.tsx
Exposes API to consumers, which allows direct passage of props to CodeMessage.
> fix(Message): Allow additional props on CodeMessage

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/ChatbotMessage/BotMessage.tsx
- packages/module/src/Message/TextMessage/TextMessage.scss
- packages/module/src/Message/TextMessage/TextMessage.tsx
In Composer AI, we were seeing bad list rendering when lists contained complex formatting. React-markdown seems to categorize the complex formatting as p tags. Since they all had an inline-block on them, this caused rendering issues when the p tag was in an li. This should fix it. I also brought in a silly, more complex example based on Composer AI.
> fix(TextMessage): Allow for more complex list output

- packages/module/src/MessageBar/MessageBar.test.tsx
- packages/module/src/MessageBar/MessageBar.tsx
We spread the PF textarea props onto this, but the third-party doesn't return the same API. This will let consumers use onChange.
> fix(MessageBar): Add onChange prop that works

- packages/module/src/MessageBox/MessageBox.scss
Noticed in Composer that we need this - having only the max width means that the box jumps around a bit resizing until it hits the max. This should fix it up.
> fix(MessageBox): Add 100% width

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/Chatbot.tsx
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/EmbeddedChatbot.tsx
We want consumers to know they should use timestamp prop for persistent Message times, given that they re-render.
> chore(docs): Add timestamp to more complex examples

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/ChatbotMessage/ChatbotMessage.md
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/ChatbotMessage/MessageWithCustomResponseActions.tsx
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/ChatbotMessage/MessageWithResponseActions.tsx
- packages/module/src/Message/Message.tsx
- packages/module/src/ResponseActions/ResponseActions.tsx
Two products have asked for response actions we don't have - this should enable consumers to add whatever they need.
Section I added: https://virtual-assistant-pr-virtual-assistant-285.surge.sh/patternfly-ai/chatbot/chatbot-messages#custom-messages-actions
> feat(ResponseActions): Allow for custom response actions

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/Messages/BotMessage.tsx
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/Messages/Messages.md
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/Messages/UserMessage.tsx
- packages/module/src/Message/Message.scss
- packages/module/src/Message/Message.tsx
Our API has name as optional - I'm letting it render as optional and then also adding truncation if it gets really long. We prioritize the timestamp at full width over the name right now - let me know if we want to prioritize the name over the timestamp instead.
> fix(Message): Truncate very long names

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/Messages/MessageWithAttachment.tsx
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/Messages/Messages.md
- packages/module/src/FileDetailsLabel/FileDetailsLabel.tsx
- packages/module/src/Message/Message.scss
- packages/module/src/Message/Message.test.tsx
- packages/module/src/Message/Message.tsx
This a breaking change, but none of our consumers are using attachments yet. I'd be happy to put back the old API if we need to maintain it.
> feat(Message): Allow for multiple attachments

- package-lock.json
- package.json
- packages/module/src/MessageBar/MessageBar.scss
- packages/module/src/MessageBar/MessageBar.test.tsx
- packages/module/src/MessageBar/MessageBar.tsx
Try contentedible div instead of textarea (was having problems on small screens in Firefox/Safari).
> fix(MessageBar): Swap out textarea

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/UI/ChatbotModal.tsx
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/UI/UI.md
- packages/module/src/ChatbotModal/ChatbotModal.scss
- packages/module/src/ChatbotModal/ChatbotModal.tsx
- packages/module/src/ChatbotModal/index.ts
- packages/module/src/CodeModal/CodeModal.scss
- packages/module/src/CodeModal/CodeModal.tsx
- packages/module/src/index.ts
- packages/module/src/main.scss
Exposing the parent of the code modal so you can put whatever you want in it and pick up the style changes we've made for chatbot.
I tested against everything in regular PF. Custom sizes and widths won't work, and the wizard won't work outside of fullscreen without some adjustments, but every other example from our site plugs in and looks non-broken to me.
> feat(ChatbotModal): Add style-able modal for general use

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/UI/ChatbotWelcomeInteraction.tsx
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/UI/UI.md
- packages/module/src/ChatbotWelcomePrompt/ChatbotWelcomePrompt.scss
- packages/module/src/ChatbotWelcomePrompt/ChatbotWelcomePrompt.tsx
- packages/module/src/ChatbotWelcomePrompt/__snapshots__/ChatbotWelcomePrompt.test.tsx.snap
- packages/module/src/MessageBox/MessageBox.scss
- packages/module/src/MessageBox/MessageBox.tsx
WelcomePrompt had spacing on top, while MessageBox didn't. I moved the spacing onto the parent since WelcomePrompt is optional. Also adding prop to control position of MessageBox content, and adding a demo for how the removal interaction could work. Design wants to demonstrate the welcome message going away when new messages are sent.
See https://virtual-assistant-pr-virtual-assistant-323.surge.sh/patternfly-ai/chatbot/ui/react/welcome-interaction/ and https://virtual-assistant-pr-virtual-assistant-323.surge.sh/patternfly-ai/chatbot/ui#welcome-interaction.
Getting a screenshots error; will debug and add those later:
```
npm run docs:screenshots
> @patternfly/virtual-assistant@1.0.0-prerelease.0 docs:screenshots
> pf-docs-framework screenshots --urlPrefix http://localhost:5001 …
```
> fix(MessageBox): Adjust spacing

- README.md
In dev mode, an explicit `npm run build` is needed, otherwise  the dist/css folder is not built.
Fixes #331
> Update to explicitly build in dev mode too

- packages/module/src/ChatbotConversationHistoryNav/ChatbotConversationHistoryDropdown.test.tsx
- packages/module/src/ChatbotConversationHistoryNav/ChatbotConversationHistoryDropdown.tsx
https://github.com/patternfly/chatbot/issues/343
fix dropdown toggle behavior on item selection
---
**Before:**
**After:**
**Unit tests:**
```
ChatbotConversationHistoryDropdown
✓ should render the dropdown (79 ms)
✓ should display the dropdown menuItems (53 ms)
✓ should invoke onSelect callback when menuitem is clicked (61 ms)
✓ should toggle the dropdown when menuitem is clicked (54 ms)
✓ should close the dropdown when user clicks outside (36 ms)
✓ should show the tooltip when the user hovers over the toggle button (40 ms)
```
> fix(ChatbotConversationHistoryDropdown): fix dropdown toggle behavior on item selection

- packages/module/src/MessageBar/MessageBar.tsx
With swap to new textarea, I missed adding the SpeechRecognition output. This should put the message content in.
> fix(MessageBar): Show SpeechRecognition output

- packages/module/src/Chatbot/Chatbot.scss
- packages/module/src/ChatbotContent/ChatbotContent.scss
- packages/module/src/FileDropZone/FileDropZone.scss
- packages/module/src/MessageBox/JumpButton.scss
- packages/module/src/MessageBox/MessageBox.scss
Allows entire chatbot to scroll like a normal website when zoom is high. Hides jump links since they won't work. Also adds responsive styles to chatbot on docked and overlay.
One example is here: https://chatbot-pr-chatbot-338.surge.sh/patternfly-ai/chatbot/overview/demo/basic-chatbot/; go to 150% or 200%.
> fix(Chatbot): Handle zoom appropriately

- packages/module/patternfly-docs/content/extensions/chatbot/design-guidelines.md
- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/ChatbotMessageBarLanguage.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/UI.md
- packages/module/src/MessageBar/MessageBar.tsx
- packages/module/src/MessageBar/MicrophoneButton.tsx
This came out of reviewing the docs - realized button stops doing recognition, but doesn't turn off. Also noticed we had a hard-coded locale in there. I adjusted that and added an example for how to manage it.
> fix(MicrophoneButton): Turn button off when recognition ends

- packages/module/src/MessageBox/JumpButton.scss
Because of the way Backstage pulls in CSS (PF before ChatBot), PatternFly overrides certain styles for the JumpButtons. Marking them should allow these to render properly in Backstage.
> fix(JumpButton): Fix JumpButton styles for Backstage

- README.md
That makes the command stick out in the readme and within Webstorm etc. even allows to click on the little green icon to run the command.
> Mark more npm commands in backticks, so they stand out as commend.

- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/ChatbotMessageBarDisabled.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/UI.md
- packages/module/src/MessageBar/SendButton.scss
- packages/module/src/MessageBar/SendButton.tsx
- packages/module/src/main.scss
Adjusted disabled state and also added a demo for always-shown send button, with an explanation on how to use it.
I migrated the button to an icon button so it picks up the same default styles Kayla's Figma kit has. This meant changing the default colors a bit for dark mode and light mode. I would appreciate a special eye on the send button in these states. I looked at Figma, but it's always helpful to get more 👀 on things.
This means that the button will now be more consistent with what's in Figma.
| State | Before | After |
|-|-|-|
| Light Default |<img width="70" alt="Screenshot 2024-12-06 at 1 47 16 PM" src="https://github.com/user-attachments/assets/47b288bc-ea6b-463e-aa75-5cca5622838e">|<img width="68" alt="Screenshot 2024-12-06 at 1 44 13 PM" …
> fix(SendButton): Adjust disabled state

- packages/module/src/Chatbot/Chatbot.scss
- packages/module/src/Chatbot/Chatbot.tsx
Was seeing some problems from this with PF React Seed - removing since it seems unnecessary. Looks like it's from when Rohit was working on this.
> fix(Chatbot): Remove html class

- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/ChatbotHeaderDrawerWithSelection.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/UI.md
- packages/module/src/ChatbotConversationHistoryNav/ChatbotConversationHistoryNav.scss
- packages/module/src/ChatbotConversationHistoryNav/ChatbotConversationHistoryNav.tsx
Allow additional menu item props to be passed down from the history nav to show the currently active conversation or apply other props as needed.
https://chatbot-pr-chatbot-374.surge.sh/patternfly-ai/chatbot/ui#drawer-with-active-conversation
> fix(ChatbotConversationHistoryNav): Add additional menu item props

- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/MessageWithCustomResponseActions.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/Messages.md
- packages/module/patternfly-docs/content/extensions/chatbot/examples/demos/Chatbot.md
- packages/module/src/ResponseActions/ResponseActionButton.test.tsx
- packages/module/src/ResponseActions/ResponseActionButton.tsx
- packages/module/src/ResponseActions/ResponseActions.scss
- packages/module/src/ResponseActions/ResponseActions.test.tsx
- packages/module/src/ResponseActions/ResponseActions.tsx
Add click state to response actions block. The last currently selected item will remain selected until you click someone else on the screen. Clients can also pass in custom tooltips or aria labels based on the clicked state.
Docs:
* https://chatbot-pr-chatbot-382.surge.sh/patternfly-ai/chatbot/messages#message-actions
* https://chatbot-pr-chatbot-382.surge.sh/patternfly-ai/chatbot/messages/#custom-message-actions
I've been working directly with Kayla on these already - she has seen them.
> feat(ResponseActions): Add click state

- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/Settings.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/UI.md
- packages/module/src/ChatbotHeader/ChatbotHeaderCloseButton.tsx
- packages/module/src/ChatbotHeader/index.ts
- packages/module/src/Settings/Settings.scss
- packages/module/src/Settings/SettingsForm.tsx
- packages/module/src/Settings/index.ts
- packages/module/src/index.ts
- packages/module/src/main.scss
Stuck this as a separate component within the chatbot: https://chatbot-pr-chatbot-360.surge.sh/patternfly-ai/chatbot/ui/react/settings/
Docs: https://chatbot-pr-chatbot-360.surge.sh/patternfly-ai/chatbot/ui/#settings
I added a dropdown that can also toggle it, but unsure if we want other stuff in this demo. I know Nicole generally wants them simple, but we don't have any guidelines for this yet.
> feat(Settings): Add settings layout

- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/MessageWithQuickStart.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/Messages.md
- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/explore-pipeline-quickstart.ts
- packages/module/src/Message/Message.test.tsx
- packages/module/src/Message/Message.tsx
- packages/module/src/Message/QuickStarts/FallbackImg.tsx
- packages/module/src/Message/QuickStarts/QuickStartTile.scss
- packages/module/src/Message/QuickStarts/QuickStartTile.tsx
- packages/module/src/Message/QuickStarts/QuickStartTileDescription.test.tsx
- packages/module/src/Message/QuickStarts/QuickStartTileDescription.tsx
- packages/module/src/Message/QuickStarts/QuickStartTileHeader.tsx
- packages/module/src/Message/QuickStarts/monitor-sampleapp-quickstart-with-image.ts
- packages/module/src/Message/QuickStarts/monitor-sampleapp-quickstart.ts
- packages/module/src/Message/QuickStarts/types.ts
- packages/module/src/main.scss
Added quick starts tile, tests, and initial shot at docs section under the Messages section: https://chatbot-pr-chatbot-377.surge.sh/patternfly-ai/chatbot/messages#messages-with-quick-start-tiles
The tile mostly reuses code from the quick starts extension, with the context and status logic removed. I added props so strings can be internationalized if needed, but the API will be a little different than the main extension.
This is based on the parent extension tile: https://quickstarts.netlify.app. I stuck a max-width on it after talking to Kayla; have not made other design changes.
> feat(QuickStartsTile): Add quick starts tile for messages

- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/ChatbotHeaderDrawerNavigation.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/UI.md
- packages/module/src/ChatbotConversationHistoryNav/ChatbotConversationHistoryNav.tsx
Nicole had mentioned that some products may require a more basic navigation look. This example documents that it's possible: https://chatbot-pr-chatbot-397.surge.sh/patternfly-ai/chatbot/ui#drawer-with-simple-menu
I am spreading menuProps onto the menu so they can change the role to navigation, etc. if needed.
> chore(docs): Add basic nav example

- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/ChatbotHeaderDrawer.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/ChatbotHeaderDrawerNavigation.tsx
Fixes a problem Erin was seeing where the page was moving.
> chore(docs): Change id on history drawer button reversal checkbox

- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/Messages.md
- packages/module/src/Message/Message.scss
- packages/module/src/Message/Message.tsx
- packages/module/src/Message/QuickResponse/QuickResponse.scss
- packages/module/src/Message/QuickResponse/QuickResponse.tsx
- packages/module/src/main.scss
Added two additional visual states to quick response labels. Only one option can be selected per block. Unlike the actions (thumbs up/down), selection persists if you click somewhere else.
State | Before | After |
|-|-|-|
|Default|<img width="102" alt="Screenshot 2025-01-09 at 3 33 58 PM" src="https://github.com/user-attachments/assets/0722cee1-d270-43ea-9a3d-3a5d7ef5e24c" />|<img width="98" alt="Screenshot 2025-01-09 at 3 33 21 PM" src="https://github.com/user-attachments/assets/5249bf59-d77b-4383-9b5a-c4f59480b10b" />|
|Hover|<img width="104" alt="Screenshot 2025-01-09 at 3 34 07 PM" src="https://github.com/user-attachments/assets/dc64ce0e-cabd-4f03-b44e-ae612e66daa2" />|<img width="104" alt="Screenshot 2025-01-09 at 3 34 02 PM" …
> feat(QuickResponse): Add active and selected states

- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/ChatbotFooter.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/ChatbotFootnote.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/demos/Chatbot.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/demos/ChatbotAttachment.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/demos/ChatbotAttachmentMenu.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/demos/EmbeddedChatbot.tsx
- packages/module/src/ChatbotConversationHistoryNav/ChatbotConversationHistoryNav.test.tsx
Left the conversation history examples alone, but swapped Lightspeed for ChatBot in the footers, etc.
> chore(docs): Remove references to Lightspeed

- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/ChatbotHeaderDrawerResizable.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/UI.md
- packages/module/src/ChatbotConversationHistoryNav/ChatbotConversationHistoryNav.test.tsx
- packages/module/src/ChatbotConversationHistoryNav/ChatbotConversationHistoryNav.tsx
Allow consumers to pass PatternFly props down to subcomponents. Created demo for resizing as well: https://chatbot-pr-chatbot-405.surge.sh/patternfly-ai/chatbot/ui#resizable-drawer
> feat(ChatbotConversationHistoryNav): Make it resizable

- packages/module/src/ChatbotConversationHistoryNav/ChatbotConversationHistoryNav.scss
Spacing between buttons and inputs was off in resizable drawer compared to regular drawer.
> fix(ChatbotConversationHistoryNav): Update spacing for resizable drawer

- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/BotMessage.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/UserMessage.tsx
- packages/module/src/Message/CodeBlockMessage/CodeBlockMessage.scss
- packages/module/src/Message/ListMessage/ListMessage.scss
- packages/module/src/Message/Message.scss
- packages/module/src/Message/Message.test.tsx
- packages/module/src/Message/Message.tsx
- packages/module/src/Message/MessageLoading.scss
- packages/module/src/Message/TextMessage/TextMessage.scss
- packages/module/src/Message/TextMessage/TextMessage.tsx
Added block quote and heading styling; also fixed small rendering bug with inline code styles.
This affects Bot and User messages:
* https://chatbot-pr-chatbot-420.surge.sh/patternfly-ai/chatbot/messages#bot-messages
* https://chatbot-pr-chatbot-420.surge.sh/patternfly-ai/chatbot/messages#user-messages
> fix(Message): Add block quotes and headings

- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/ChatbotMessageBarAttach.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/demos/ChatbotAttachmentMenu.tsx
- packages/module/src/MessageBar/AttachButton.tsx
Saw this in scrum - we're using this too, so pulling it in.
There is a required input for react-dropzone. We should hide it from screenreaders since it's not something users can interact with.
See https://github.com/patternfly/patternfly-react/pull/11438.
> fix(AttachButton): Hide input from screenreaders

- packages/module/src/MessageBar/MessageBar.tsx
Fixes #429 
Adds dependencies to the `handleKeyDown` callback so that it recognizes changes to the enablement of the send and stop buttons.
Also fixes an issue with a console error message for updating the MessageBar while already updating.
> fix(MessageBar): Fix to handle enter key when send button initially disabled

- packages/module/src/Message/QuickStarts/QuickStartTile.scss
- packages/module/src/ResponseActions/ResponseActions.scss
Drop min-width on QuickStartTile so it performs well in drawers, etc. and added better targeting to response actions. This is following testing the chatbot in a resizable drawer layout.
> fix(QuickStarts/ResponseActions): CSS updates

- package-lock.json
- package.json
- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/BotMessage.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/UserMessage.tsx
- packages/module/src/Message/Message.test.tsx
- packages/module/src/Message/Message.tsx
- packages/module/src/Message/TableMessage/TableMessage.scss
- packages/module/src/Message/TableMessage/TableMessage.tsx
- packages/module/src/Message/TableMessage/TbodyMessage.tsx
- packages/module/src/Message/TableMessage/TdMessage.tsx
- packages/module/src/Message/TableMessage/ThMessage.tsx
- packages/module/src/Message/TableMessage/TheadMessage.tsx
- packages/module/src/Message/TableMessage/TrMessage.tsx
- packages/module/src/Message/TextMessage/TextMessage.scss
- packages/module/src/main.scss
Wire Message to re-route tables to PF tables.
These are just basic tables, with no bells and whistles. I am defaulting to the mobile breakpoint, but we could also do a regular table at certain widths. Let me know what you want to do here - I am just copying Figma right now. I am also letting this be full width, but it will resize down if you change the device viewport or screen size - let me know if that's not what we want.
I am defining a default aria label, allowing passage of aria-labels, and also attempting to generate these based on headers. I have written tests for full tables, blank tables, headerless tables, cell-less tables, 1 column-tables, and 1-cell tables. Let me know if you can break this and we'll add another test.
**Doc changes:**
* …
> feat(TableMessage): Add support for PatternFly tables

- packages/module/src/MessageBar/MessageBar.scss
- packages/module/src/MessageBar/MessageBar.tsx
Pulling back in attempt from November  - rebased and checked against our current main example at different screen sizes.
I sent this Kayla's way on Slack - she seemed ok with it.
> Replace contenteditable div with PatternFly text area

- packages/module/src/MessageBar/MessageBar.scss
Input bar works in Ansible, allegedly. ShadowBot team was noticing that the specificity needed to be a little higher. This should get them where they need to be.
> fix(MessageBar): Add additional specificity to input bar

- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/Messages.md
- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/UserMessageWithExtraContent.tsx
- packages/module/src/Message/Message.test.tsx
- packages/module/src/Message/Message.tsx
Closes https://github.com/patternfly/chatbot/issues/418
> Enhance Message Component to Support ReactNode in Content via extraContent Prop

- packages/module/src/MessageBar/MessageBar.tsx
- packages/module/src/MessageBar/MicrophoneButton.tsx
We want to allow for manual configuration of tooltips by consumers - this allows passage of props.
> fix(MessageBar): Allow passing props to button tooltip

- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/ChatbotHeaderDrawer.tsx
- packages/module/src/ChatbotConversationHistoryNav/ChatbotConversationHistoryNav.scss
- packages/module/src/ChatbotConversationHistoryNav/ChatbotConversationHistoryNav.test.tsx
- packages/module/src/ChatbotConversationHistoryNav/ChatbotConversationHistoryNav.tsx
- packages/module/src/ChatbotConversationHistoryNav/EmptyState.tsx
- packages/module/src/ChatbotConversationHistoryNav/LoadingState.tsx
Add skeleton loading state that can be controlled via isLoading prop on drawer. Error state is controlled via the errorState prop.
I made the history panel and aria-live region so it will announce updates, but unsure if that's super annoying. Would love to get Eric's opinion on this.
Docs change: https://chatbot-pr-chatbot-445.surge.sh/patternfly-ai/chatbot/ui#drawer-with-search-and-new-chat-button
> feat(ChatbotConversationHistoryNav): Add loading state and error state

- packages/module/src/Message/Message.tsx
- The use case is end users need to add additional plugins like `rehype-raw` to the underlying react-dropdown usage in <Message/>
> feat(Message): Allow additional rehype plugins to be passed to the message component

- package-lock.json
- package.json
- packages/module/package.json
- packages/module/src/Chatbot/Chatbot.scss
- packages/module/src/Message/LinkMessage/LinkMessage.tsx
- packages/module/src/Message/ListMessage/ListMessage.scss
- packages/module/src/Message/Message.test.tsx
- packages/module/src/Message/Message.tsx
- packages/module/src/Message/TextMessage/TextMessage.scss
- packages/module/src/__mocks__/rehype-external-links.ts
- packages/module/src/__mocks__/rehype-sanitize.ts
- packages/module/src/__mocks__/rehype-unwrap-images.tsx
- packages/module/src/main.scss
Add ability to handle external links. External links are marked with an icon. This PR also migrates us from `<a>` tags to PatternFly `Button` elements.
I am also dropping the dom-purify library - we don't need it since we switched the text input in the footer. We are adjusting the position of react-table in the other Message PR. 
Downstream consumers may need to mock rehype-external-links and rehype-sanitize in Jest since they are ESM imports.
You can see the change in the look and feel in the docs: https://chatbot-pr-chatbot-446.surge.sh/patternfly-ai/chatbot/messages#bot-messages
We may want to adjust the user message colors (see below). I'd like to open up a larger discussion over whether we want to render Markdown in user messages on Thursday, so unsure if we want to spend much time …
> feat(Message): Add ability to handle external links

- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/BotMessage.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/UserMessage.tsx
- packages/module/src/Message/ErrorMessage/ErrorMessage.tsx
- packages/module/src/Message/Message.test.tsx
- packages/module/src/Message/Message.tsx
Add inline error message for Message component.
Docs: 
* https://chatbot-pr-chatbot-465.surge.sh/patternfly-ai/chatbot/messages#bot-messages
* https://chatbot-pr-chatbot-465.surge.sh/patternfly-ai/chatbot/messages#user-messages
> feat(Message): Add inline error message

- packages/module/src/MessageBar/MessageBar.scss
ShadowBox extension team is using vite. Styles are getting pulled in wrong order, with PF first. This means that these styles are being overridden in their implementation. This will hopefully fix their issue.
> fix(MessageBar): Make resize and form-control overrides more important

- packages/module/src/SourcesCard/SourcesCard.scss
Backstage is not handling link colors appropriately - explicitly define these.
> fix(SourcesCard): Add explicit links style

- packages/module/src/ChatbotModal/ChatbotModal.scss
- packages/module/src/CodeModal/CodeModal.scss
- packages/module/src/FileDetailsLabel/FileDetailsLabel.scss
- packages/module/src/Message/QuickResponse/QuickResponse.tsx
- packages/module/src/Message/TableMessage/TableMessage.scss
- packages/module/src/Message/UserFeedback/UserFeedback.scss
- packages/module/src/MessageBar/MessageBar.scss
- packages/module/src/SourceDetailsMenuItem/SourceDetailsMenuItem.scss
- packages/module/src/SourcesCard/SourcesCard.scss
- packages/module/src/TermsOfUse/TermsOfUse.scss
Some consumers have less control over style order. This was causing problems when PatternFly overrode ChatBot overrides. This should allow these consumers to continue using ChatBot with a good level of success.
> fix(Styles): Allow for graceful failure when styles pulled in wrong order

- packages/module/src/ChatbotWelcomePrompt/ChatbotWelcomePrompt.scss
Cards should be the same height and shouldn't scroll. I think this crept in as part of docs changes. Regardless, we should handle different text lengths well.
| Before | After | 
|-|-|
|<img width="927" alt="Screenshot 2025-03-17 at 10 42 11 AM" src="https://github.com/user-attachments/assets/d5e3564c-21a8-4f45-86aa-72da61689dfb" />|<img width="950" alt="Screenshot 2025-03-17 at 10 40 46 AM" src="https://github.com/user-attachments/assets/7e8286b4-19e0-4a05-b8f0-1c3300283c75" />
|<img width="511" alt="Screenshot 2025-03-17 at 10 42 02 AM" src="https://github.com/user-attachments/assets/70520501-6636-4a8c-8295-a7c4ac2b0842" />|<img width="505" alt="Screenshot 2025-03-17 at 10 40 38 AM" src="https://github.com/user-attachments/assets/c5506d8d-2f5b-4f7a-affe-c2d7b877120c" />
> fix(ChatbotWelcomePrompt): Cards should be gallery layout

- packages/module/src/MessageBar/MessageBar.scss
Red Hat Developer Hub is defaulting to monospace. PatternFly textareas inherit the font-family. This is causing a regression for them. We can declare a font-family in ChatBot to resolve this if we want to.
> fix(MessageBar): RHDH-specific font size declaration

- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/MessageWithQuickResponses.tsx
Quick Response can take additional label props - document how to do this.
See https://chatbot-pr-chatbot-500.surge.sh/patternfly-ai/chatbot/messages#messages-with-quick-responses
> chore(docs): Add demo for disabled quick response

- packages/module/src/Message/Message.test.tsx
- packages/module/src/Message/Message.tsx
Lightspeed was wondering if we could allow prop passing on links - putting up for after code freeze.
> feat(Message): Allow passage of Button props onto links

- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/ChatbotHeaderDrawer.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/ChatbotHeaderDrawerResizable.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/UI.md
- packages/module/src/ChatbotConversationHistoryNav/ChatbotConversationHistoryNav.test.tsx
- packages/module/src/ChatbotConversationHistoryNav/ChatbotConversationHistoryNav.tsx
Added empty state and no-results state for search. Updated demos/tests.
See https://chatbot-pr-chatbot-498.surge.sh/patternfly-ai/chatbot/ui#drawer-with-search-and-new-chat-button
> feat(ChatbotConversationHistoryNav): Add empty/no results states

- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/BotMessage.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/UserMessage.tsx
- packages/module/src/Message/Message.scss
- packages/module/src/Message/Message.test.tsx
- packages/module/src/Message/Message.tsx
- packages/module/src/Message/MessageInput.tsx
Add prop to trigger edit mode and display form when edit mode is on. Add examples/tests.
Docs: https://chatbot-pr-chatbot-505.surge.sh/patternfly-ai/chatbot/messages#user-messages
> feat(Message): Add ability to edit user prompt

- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/BotMessage.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/FileDetailsLabel.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/UserMessage.tsx
Closes: #433 
The following examples will be migrated:
- Bot Messages
- User Messages
- Attachment label
> chore(messages): migrate demos from radio to select

- packages/module/src/MessageBar/MessageBar.test.tsx
- packages/module/src/MessageBar/MessageBar.tsx
Fixes [Message bar placeholders should be customizable](https://github.com/patternfly/chatbot/issues/528)
Adds props to the `MessageBar` component to accept overrides for the placeholder text and listening text.
Adds unit tests to validate the override capabilities.
> feat(MessageBar): Allow customization of placeholder text

- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/MessageWithQuickResponses.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/MessageWithQuickStart.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/MessageWithSources.tsx
- packages/module/src/Message/Message.tsx
- packages/module/src/Message/QuickResponse/QuickResponse.tsx
- packages/module/src/Message/QuickStarts/QuickStartTile.tsx
- packages/module/src/SourcesCard/SourcesCard.scss
- packages/module/src/SourcesCard/SourcesCard.tsx
I'm breaking the density ticket into a series of smaller tickets so they'll be easier to review. This is only the spacing changes for these items - font, etc. will be adjusted in a separate PR.
Added isCompact prop used to control information density in Sources cards, Quick Starts tiles, and quick response labels.
https://chatbot-pr-chatbot-519.surge.sh/patternfly-ai/chatbot/messages#messages-with-quick-responses
https://chatbot-pr-chatbot-519.surge.sh/patternfly-ai/chatbot/messages#messages-with-sources
https://chatbot-pr-chatbot-519.surge.sh/patternfly-ai/chatbot/messages#messages-with-quick-start-tiles
> feat(Message): Add compact sources, quick starts, and quick responses

- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/ChatbotContainer.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/ChatbotHeaderTitle.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/ChatbotModal.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/TermsOfUse.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/TermsOfUseCompact.tsx
> chore(ui): migrate demos from radio to select

- packages/module/src/AttachmentEdit/AttachmentEdit.test.tsx
- packages/module/src/AttachmentEdit/AttachmentEdit.tsx
- packages/module/src/CodeModal/CodeModal.test.tsx
- packages/module/src/CodeModal/CodeModal.tsx
- packages/module/src/PreviewAttachment/PreviewAttachment.test.tsx
- packages/module/src/PreviewAttachment/PreviewAttachment.tsx
Fixes:
https://github.com/patternfly/chatbot/issues/551
**Description:**
add footer action button text props in Preview/Edit Attachment components.
> add footer action button text props in Attachment components.

- packages/module/src/ChatbotHeader/ChatbotHeaderSelectorDropdown.tsx
> feat(ChatbotHeaderSelectorDropdown): allow resizing for dropdown header

- package-lock.json
- packages/module/package.json
- packages/module/src/Message/Message.test.tsx
- packages/module/src/Message/Message.tsx
- packages/module/src/Message/Plugins/rehypeMoveImagesOutOfParagraphs.ts
By default, Markdown renderer places images in p tags. We have a plugin already there to remove these from paragraphs that only contain images, but this didn't affect cases where you had both text and an image inline with each other. Added a plugin to modify the syntax tree in this case.
This came partially out of a product request (related to https://github.com/patternfly/chatbot/pull/557) and I wanted to get this in before I forget how to do this.
Before:
After:
This is the difference in Markdown:
```
I am a block level image: 
I am an inline image: ![Multi-colored wavy lines on a black background](https://cdn.dribbble.com/userupload/10651749/file/original-8a07b8e39d9e8bf002358c66fce1223e.gif)
```
> fix(Message): Images should always render as separate block-level element

- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/BotMessage.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/UserMessage.tsx
- packages/module/src/Message/CodeBlockMessage/CodeBlockMessage.scss
- packages/module/src/Message/CodeBlockMessage/CodeBlockMessage.tsx
- packages/module/src/Message/CodeBlockMessage/ExpandableSectionForSyntaxHighlighter.tsx
- packages/module/src/Message/Message.test.tsx
- packages/module/src/Message/Message.tsx
This was a request from RHDH product manager - wanted to be able to make code blocks optionally expandable. They were fine with having it applied to all code blocks in message - they envision having it applied to all user messages by default.
Kayla wanted the truncated toggle applied by default - it sounds like design will have general PF migrate in that direction soon.
Docs: https://chatbot-pr-chatbot-556.surge.sh/patternfly-ai/chatbot/messages (go to user or bot message and select "expandable code" option from dropdown.)
> feat(CodeBlockMessage/Message): Add expandable code block

- packages/module/patternfly-docs/content/extensions/chatbot/examples/demos/ChatbotAttachment.tsx
- packages/module/src/FileDropZone/FileDropZone.test.tsx
- packages/module/src/FileDropZone/FileDropZone.tsx
- packages/module/src/MessageBar/AttachButton.test.tsx
- packages/module/src/MessageBar/AttachButton.tsx
- packages/module/src/MessageBar/MessageBar.tsx
Fixes:
https://github.com/patternfly/chatbot/issues/563
This PR allows specific file types during Attachment upload, which enhances the user experience by reducing invalid submissions.
Accept the `allowedFileTypes` as prop and mapping it to the `accept` property in `react-dropzone`.
```js
<MessageBar
{...otherProps}
allowedFileTypes={{
'text/plain': ['.txt'],
'application/json': ['.json'],
'application/yaml': ['.yaml', '.yml']
}}
/>
```
Notice the `.csv` file is disabled and  only `.json`, `.txt` and `.yaml` files are enabled.
```
Attach button
✓ should set correct accept attribute on file input (24 ms)
✓ should call onAttachAccepted when file type is accepted (12 ms)
✓ should not call onAttachAccepted when file type is not accepted (10 ms)
```
> Allow Specific File Types in Attachment Upload 

- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/BotMessage.tsx
Looks like a rebase gave us some duplicate examples in the BotMessage section.
> chore(docs): Remove duplicate examples

- packages/module/patternfly-docs/content/extensions/chatbot/examples/demos/ChatbotAttachment.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/demos/ChatbotAttachmentMenu.tsx
- packages/module/src/FileDropZone/FileDropZone.test.tsx
- packages/module/src/FileDropZone/FileDropZone.tsx
- packages/module/src/MessageBar/AttachButton.test.tsx
- packages/module/src/MessageBar/AttachButton.tsx
- packages/module/src/MessageBar/MessageBar.tsx
This was a new request from RHDH.
Added some more potentially-useful props to our API and added a jailbreak option for things I'm not specifying in case of sudden product needs. I'm not adding all explicitly to the API, just the ones that are easy to test. Everything else should be able to fit through via the spread operator.
I'm leaving the ...props spread on FileDropZone as-is since I don't want to break anyone.
> fix(MessageBar/FileDropZone): Allow passing additional props to react-dropzone

- packages/module/src/Message/TextMessage/TextMessage.scss
Previously spacing could vary based on size of parent message - switching to 100% of space.
| Before | After |
|-|-|
> fix(ResponseActions): Adjust spacing so it's consistent

- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/ChatbotHeaderDrawer.tsx
- packages/module/src/ChatbotConversationHistoryNav/ChatbotConversationHistoryNav.test.tsx
- packages/module/src/ChatbotConversationHistoryNav/ChatbotConversationHistoryNav.tsx
Fixes:
https://github.com/patternfly/chatbot/issues/596
Add support for disabling `New chat` button.
**Demo:**
https://github.com/user-attachments/assets/02bea102-1a63-4e5a-a0bb-9642ba90bffa
> add support for disabling new chat button

- package-lock.json
- package.json
- packages/module/package.json
- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/ChatbotHeaderBasic.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/UI.md
- packages/module/patternfly-docs/content/extensions/chatbot/examples/demos/Chatbot.md
- packages/module/src/ChatbotConversationHistoryNav/ChatbotConversationHistoryNav.tsx
- packages/module/src/ChatbotHeader/ChatbotHeaderNewChatButton.test.tsx
- packages/module/src/ChatbotHeader/ChatbotHeaderNewChatButton.tsx
- packages/module/src/ChatbotHeader/index.ts
- packages/module/src/FileDetails/__snapshots__/FileDetails.test.tsx.snap
- packages/module/src/FileDetailsLabel/__snapshots__/FileDetailsLabel.test.tsx.snap
Closes #509. Updated @patternfly/documentation-framework to 6.16.0 for icon. Buttons in the header and basic chatbot demos, when clicked, do not have functionality as of this moment. If needed, these buttons can also be added to other demos.
> feat(Button): add new chat button and icon

- packages/module/src/MessageBar/MessageBar.tsx
Languages that rely on IME keyboards may use the enter key for final text selection on Mac. The MessageBar also uses enter key for submit. The result was that IME input, such as Japanese, was prematurely submitted. I added an additional check for whether the onCompositionEnd event is complete and also added some additional handling for Safari, which is a little bit of a special case. This should resolve the issue on Mac. I manually checked Edge, Chrome, Safari, and Firefox on my machine with a Japanese keyboard.
Assisted-by: Cursor (used to generate boilerplate for handleCompositionStart/End, etc.)
https://www.stum.de/2016/06/24/handling-ime-events-in-javascript/ helped me resolve the issue with Safari - we have to use "which" for now - the less-deprecated ways of checking just register …
> fix(MessageBar): Fix IME language handling

- packages/module/src/ChatbotConversationHistoryNav/ChatbotConversationHistoryNav.test.tsx
- packages/module/src/ChatbotConversationHistoryNav/ChatbotConversationHistoryNav.tsx
Allow for controlled inputs and other customizations by passing props down.
> fix(ChatbotConversationHistoryNav): Pass search input props

- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/ChatbotHeaderDrawerWithPin.tsx
- packages/module/src/ChatbotConversationHistoryNav/ChatbotConversationHistoryDropdown.tsx
- packages/module/src/ChatbotConversationHistoryNav/ChatbotConversationHistoryNav.tsx
Also updating pin/unpin demo so dropdown is focused when a change is made.
Closed other PR since it was created before token refresh - we'd never see surge update correctly ever again.
> fix(ChatbotConversationHistoryNav): Allow passing custom ids to dropdowns

- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/MessageWithFeedback.tsx
- packages/module/src/Message/UserFeedback/UserFeedback.test.tsx
- packages/module/src/Message/UserFeedback/UserFeedback.tsx
IFD wants to enable legal text in the feedback form under the text input.
Also updated component to accept additional props on all pieces while I was in there.
Assisted-by: Cursor (used for the boilerplate parts of test writing only)
> feat(UserFeedback): Allow custom children

- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/UserMessageWithExtraContent.tsx
https://chatbot-pr-chatbot-652.surge.sh/patternfly-ai/chatbot/messages#custom-message-content
> chore(demos): Update hr color in installer demo

- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/MessageWithToolResponse.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/Messages.md
- packages/module/src/Message/Message.test.tsx
- packages/module/src/Message/Message.tsx
- packages/module/src/ToolResponse/ToolResponse.scss
- packages/module/src/ToolResponse/ToolResponse.test.tsx
- packages/module/src/ToolResponse/ToolResponse.tsx
- packages/module/src/ToolResponse/index.ts
- packages/module/src/index.ts
- packages/module/src/main.scss
Added new tool response component with demo and tests.
Here are some screenshots in situ:
Demo: https://chatbot-pr-chatbot-662.surge.sh/patternfly-ai/chatbot/messages#messages-with-tool-responses
> feat(ToolResponse): Add component

- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/FilePreview.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/Messages.md
- packages/module/patternfly-docs/content/extensions/chatbot/examples/UI/UI.md
- packages/module/src/FilePreview/FilePreview.scss
- packages/module/src/FilePreview/FilePreview.test.tsx
- packages/module/src/FilePreview/FilePreview.tsx
- packages/module/src/FilePreview/index.ts
- packages/module/src/index.ts
- packages/module/src/main.scss
Added "can't be previewed" modal. Will add image preview modal in separate PR.
Docs: https://chatbot-pr-chatbot-664.surge.sh/patternfly-ai/chatbot/messages#file-preview
> feat(FilePreview): Add file preview modal
