patternfly/chatbot

- package-lock.json
- package.json
- packages/module/src/VirtualAssistant/__snapshots__/VirtualAssistant.test.tsx.snap
- Changed eslint-plugin-markdown version to avoid lint failures
- Written missing snapshot
- Changed Octokit version
> Change eslint-plugin-markdown version

- README.md
Initialize contribution guide for the assistant repo
> Add initial contribution guide to README.md

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/VirtualAssistant/VirtualAssistantConversationAlert.tsx
- packages/module/src/ConversationAlert/ConversationAlert.tsx
- Uses the same content as the Alert
> Allow ConversationAlerts to hold content

- packages/module/src/AssistantMessageEntry/AssistantMessageEntry.tsx
- packages/module/src/LoadingMessage/LoadingMessage.tsx
- packages/module/src/UserMessageEntry/UserMessageEntry.tsx
- Use ComponentType instead of ComponentClass
- This supports Functional Components as well
> Update icon types

- packages/module/src/AssistantMessageEntry/AssistantMessageEntry.tsx
- packages/module/src/ConversationAlert/ConversationAlert.tsx
- packages/module/src/VirtualAssistant/VirtualAssistant.tsx
- Allows to customize the text
> Use ReactNode instead of string whenever is possible

- packages/module/src/VirtualAssistant/VirtualAssistant.tsx
Jira: https://issues.redhat.com/browse/RHCLOUD-33950
> fix: increase default size of virtual assistant

- cypress/component/VirtualAssistant.cy.tsx
- packages/module/src/VirtualAssistant/VirtualAssistant.tsx
- packages/module/src/VirtualAssistant/__snapshots__/VirtualAssistant.test.tsx.snap
Jira: https://issues.redhat.com/browse/RHCLOUD-33980
Old
New
> fix: restyle VA footer

- packages/module/src/AssistantMessageEntry/AssistantMessageEntry.tsx
- options are disabled after one is chosen
- update styling for selected and unselected options
[RHCLOUD-32735](https://issues.redhat.com/browse/RHCLOUD-32735)
> fix: track selected option for styling

- packages/module/src/AssistantMessageEntry/AssistantMessageEntry.tsx
> Fix: Add title to VA message

- packages/module/src/FileDetailsLabel/FileDetailsLabel.scss
- packages/module/src/index.ts
I missed adding dark mode styling on the first pass - this should match the design.
> fix(FileDetailsLabel): Add dark mode styling

- packages/module/src/ChatbotHeader/ChatbotHeaderOptionsDropdown.tsx
On RTL mode in full screen mode, the kebab was getting cut off. This should prevent that.
Fixes https://github.com/patternfly/virtual-assistant/issues/109
> fix(ChatbotHeaderOptionsDropdown): Prevent overflow on kebab menu

- packages/module/src/FileDetailsLabel/FileDetailsLabel.scss
This is a temporary fix before I migrate to Kayla's work so we don't show something terribad in a demo.
> fix(FileDetailsLabel): Fix obvious hover problem on dark mode

- packages/module/patternfly-docs/content/extensions/virtual-assistant/about-virtual-assistant.md
> chore(docs): Update about page

- packages/module/src/Message/CodeBlockMessage/CodeBlockMessage.scss
- packages/module/src/Message/TextMessage/TextMessage.scss
Kayla's team is working out a more PatternFly-compliant system for user messages. This not yet ready. However, she approved this as a short-term gap fix so we can address the bug Rohit's team filed. Rohit's team was seeing problems with inline code and also block-level code headings on dark mode. This should address both for now.
Fixes https://github.com/patternfly/virtual-assistant/issues/137
> fix(CodeBlock): Fix dark mode issues

- packages/module/src/FileDetails/FileDetails.scss
- packages/module/src/FileDetails/FileDetails.tsx
- packages/module/src/FileDetailsLabel/FileDetailsLabel.scss
- packages/module/src/FileDetailsLabel/FileDetailsLabel.tsx
FileDetails:
| Before | After |
|-|-|
|<img width="100" alt="Screenshot 2024-09-11 at 11 31 46 AM" src="https://github.com/user-attachments/assets/0fd75754-0ca8-40ff-8ecc-62e96accd28d">|<img width="77" alt="Screenshot 2024-09-11 at 11 44 47 AM" src="https://github.com/user-attachments/assets/144bf632-b7f4-4c11-be09-2065533ebbd9">|
|<img width="91" alt="Screenshot 2024-09-11 at 11 31 50 AM" src="https://github.com/user-attachments/assets/1b3a4f43-d545-44d9-a712-402c7e127514">|<img width="81" alt="Screenshot 2024-09-11 at 11 44 51 AM" src="https://github.com/user-attachments/assets/bcadb967-26b2-42e3-8378-56a795eafe72">
FileDetailsLabel:
|State|Before| After |
|-|-|-|
|Default|<img width="202" alt="Screenshot 2024-09-13 at 10 59 23 AM" …
> fix(FileDetails/FileDetailsLabel): Update styles to use Kayla's tokens

- packages/module/src/ChatbotToggle/ChatbotToggle.scss
- packages/module/src/ChatbotToggle/ChatbotToggle.tsx
- packages/module/src/Message/Message.scss
- packages/module/src/main.scss
This updates the tokens used in:
- the toggle to open/close the chatbot
- the send button in the message bar
- the inline code block (esp in dark theme)
> fix: button and toggle tokens

- packages/module/src/CodeModal/CodeModal.scss
- packages/module/src/CodeModal/CodeModal.tsx
This one depends on https://github.com/patternfly/virtual-assistant/pull/135 merging first; I have commits from there in here.
Kayla says this is fine, so we're good to review after #135 is in.
> fix(CodeModal): Adjust styles to match Kayla's design

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/ChatbotAttachment.tsx
- packages/module/src/Chatbot/Chatbot.scss
- packages/module/src/FileDropZone/FileDropZone.scss
- packages/module/src/FileDropZone/FileDropZone.tsx
This one depends on https://github.com/patternfly/virtual-assistant/pull/135 merging first; I have commits from there in here.
| View | Before | After |
|-|-|-|
|Overlay | <img width="506" alt="Screenshot 2024-09-16 at 4 35 40 PM" src="https://github.com/user-attachments/assets/6936b76e-88d0-4403-bcfa-7bffdc2e2216">|<img width="503" alt="Screenshot 2024-09-16 at 4 32 12 PM" src="https://github.com/user-attachments/assets/ef652a9a-2796-4288-93c4-c957e6593f87">|
| Docked | N/A |<img width="492" alt="Screenshot 2024-09-16 at 4 32 19 PM" src="https://github.com/user-attachments/assets/f8154761-1248-4e85-a4d2-d09c508096ff">
| Fullscreen | N/A |<img width="1412" alt="Screenshot 2024-09-16 at 4 32 27 PM" src="https://github.com/user-attachments/assets/f963bd6b-9ef1-4a9c-b318-3a3362491b29">
> fix(FileDropZone): Update to match Kayla's design

- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/ChatbotHeader/ChatbotHeader.md
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/ChatbotHeader/ChatbotHeaderBasic.tsx
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/ChatbotHeader/ChatbotHeaderTitle.tsx
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/Chatbot.tsx
- packages/module/patternfly-docs/content/extensions/virtual-assistant/examples/demos/ChatbotAttachment.tsx
- packages/module/src/ChatbotHeader/ChatbotHeader.scss
- packages/module/src/ChatbotHeader/ChatbotHeaderMenu.tsx
- packages/module/src/ChatbotHeader/ChatbotHeaderOptionsDropdown.tsx
- packages/module/src/ChatbotHeader/ChatbotHeaderTitle.tsx
Make icons larger, rotate the selector dropdown icon, and make sure they're centered.
> fix(Header): Update icons

- packages/module/src/MessageBar/MessageBar.scss
There should be more space to the right of the action buttons in the message bar.
> fix(MessageBar): Adjust padding

- packages/module/src/Message/TextMessage/TextMessage.scss
Mark wants to adjust these for visibility/contrast reasons.
> fix(Message): Remove background and adjust padding for Bot messages

- packages/module/src/MessageBar/MicrophoneButton.tsx
Tooltips with dynamic content should follow this example: https://staging-v6.patternfly.org/components/tooltip#on-icon-with-dynamic-content
> fix(MicrophoneButton): Tooltip should be an aria-live region

- packages/module/src/AttachMenu/AttachMenu.tsx
- packages/module/src/MessageBox/MessageBox.tsx
Needs to match PF guidelines for scrolling content.
> fix(MessageBox): MessageBox should have tabIndex, role, and aria-label

- packages/module/src/ChatbotHeader/ChatbotHeaderMenu.tsx
- packages/module/src/Message/CodeBlockMessage/CodeBlockMessage.tsx
- packages/module/src/MessageBar/AttachButton.tsx
- packages/module/src/MessageBar/MicrophoneButton.tsx
- packages/module/src/MessageBar/SendButton.tsx
- packages/module/src/MessageBox/JumpButton.tsx
- packages/module/src/ResponseActions/ResponseActionButton.tsx
Closes: https://github.com/patternfly/virtual-assistant/issues/218
> fix: remove redundant aria-describedby attributes

- packages/module/src/Message/Message.scss
- packages/module/src/Message/MessageLoading.scss
|Before|After|
|-|-|
|<img width="279" alt="Screenshot 2024-10-18 at 10 39 06 AM" src="https://github.com/user-attachments/assets/3fd60abb-7c21-4dea-ad25-5e4d33b8f711">|<img width="304" alt="Screenshot 2024-10-18 at 10 39 13 AM" src="https://github.com/user-attachments/assets/2e8afa10-430e-4734-ac69-54f529771ce8">
|<img width="301" alt="Screenshot 2024-10-18 at 10 40 18 AM" src="https://github.com/user-attachments/assets/1d104d8d-0d09-4b38-ab8f-58371cc9270f">|<img width="300" alt="Screenshot 2024-10-18 at 10 40 29 AM" src="https://github.com/user-attachments/assets/4c2741de-59d0-4452-ba5f-3a08c17cd809">
| https://github.com/user-attachments/assets/a1f381d1-3676-4da7-8ec7-de3309ed2d94 | https://github.com/user-attachments/assets/e3554a51-288b-4c7f-b106-7957c737c90d |
> fix(Message/MessageLoading/FileDetailsLabel): Update to PF tokens

- packages/module/src/CodeModal/CodeModal.scss
- packages/module/src/CodeModal/CodeModal.tsx
- packages/module/src/main.scss
> Cherry pick issue 276

- packages/module/src/ChatbotContent/ChatbotContent.scss
- packages/module/src/ChatbotFooter/ChatbotFooter.scss
- packages/module/src/ChatbotFooter/ChatbotFooter.tsx
- packages/module/src/MessageBox/MessageBox.scss
Width should be limited to improve readability as screen sizes increase.
> chore(MessageBar/ChatbotContent): On fullscreen and embedded, limit width

- packages/module/src/SourcesCard/SourcesCard.scss
Noticed bug in Composer AI on mobile - this should fix it.
> fix(SourcesCard): Remove fixed width

- packages/module/src/Message/Message.test.tsx
- packages/module/src/MessageBar/AttachButton.test.tsx
- packages/module/src/MessageBar/AttachButton.tsx
- packages/module/src/MessageBar/MessageBar.test.tsx
- packages/module/src/MessageBar/MessageBar.tsx
- packages/module/src/MessageBar/MicrophoneButton.tsx
- packages/module/src/MessageBar/SendButton.test.tsx
- packages/module/src/MessageBar/SendButton.tsx
- packages/module/src/MessageBar/StopButton.test.tsx
- packages/module/src/MessageBar/StopButton.tsx
File                                     | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-----------------------------------------|---------|----------|---------|---------|-------------------
All files                                |   41.62 |    48.27 |   28.69 |   41.79 |                   
AttachMenu                              |      80 |       70 |   33.33 |   77.77 |                   
AttachMenu.tsx                         |      80 |       70 |   33.33 |   77.77 | 61-72             
AttachmentEdit                          |       0 |        0 |       0 |       0 |                   
AttachmentEdit.tsx                     |       0 |        0 |       0 |       0 | 4-63              
Chatbot                                 |    62.5 |     12.5 |   33.33 |      60 | …
> Get test coverage up to ~40%

- packages/module/src/Chatbot/Chatbot.scss
Design was looking for better differentiation between the chatbot and any body content.
Box shadows: https://virtual-assistant-pr-virtual-assistant-321.surge.sh/patternfly-ai/chatbot/overview/demo/basic-chatbot/
> fix(Chatbot): Change box shadow

- packages/module/src/ChatbotFooter/ChatbotFooter.scss
Make footer flex so we can use it in tab layouts.
> fix(ChatbotFooter): Remove fixed width on footer

- packages/module/src/ChatbotFooter/ChatbotFooter.scss
- packages/module/src/ChatbotHeader/ChatbotHeader.scss
Docked mode now has borders similar to the ones present in overlay mode. Came out of spec for user testing work.
> fix(ChatbotFooter/ChatbotHeader): Add borders in docked mode

- packages/module/src/ChatbotHeader/ChatbotHeader.scss
- packages/module/src/MessageBar/AttachButton.scss
- packages/module/src/MessageBar/MessageBar.scss
- packages/module/src/MessageBar/MicrophoneButton.scss
- packages/module/src/MessageBar/StopButton.scss
- packages/module/src/MessageBox/JumpButton.scss
- packages/module/src/SourcesCard/SourcesCard.scss
- packages/module/src/main.scss
| Button | State | Before (Light) | After (Light) | Before (Dark) | After (Dark) |
|-|-|-|-|-|-|
|Attach|Default|<img width="54" alt="Screenshot 2025-01-21 at 2 06 50 PM" src="https://github.com/user-attachments/assets/d05a3c47-0e59-4617-8a4b-b24b253f6c4b" />|<img width="39" alt="Screenshot 2025-01-21 at 2 11 51 PM" src="https://github.com/user-attachments/assets/5d02ecc9-d22d-4b3e-8987-bb1933d3bdf4" />|<img width="41" alt="Screenshot 2025-01-21 at 2 14 57 PM" src="https://github.com/user-attachments/assets/6cdea71b-68a1-43f4-88ed-5235a8942ba7" />|<img width="50" alt="Screenshot 2025-01-21 at 2 17 43 PM" src="https://github.com/user-attachments/assets/f29a2372-a2fd-4539-8189-7d0e31351703" />
|Attach|Hover|<img width="65" alt="Screenshot 2025-01-21 at 2 07 04 PM" …
> Add additional button states for stop, attach, and microphone buttons

- packages/module/src/AttachmentEdit/AttachmentEdit.test.tsx
- packages/module/src/Chatbot/Chatbot.test.tsx
- packages/module/src/ChatbotAlert/ChatbotAlert.test.tsx
- packages/module/src/ChatbotContent/ChatbotContent.test.tsx
- packages/module/src/ChatbotFooter/ChatbotFooter.test.tsx
- packages/module/src/ChatbotFooter/ChatbotFooternote.test.tsx
- packages/module/src/ChatbotHeader/ChatbotHeader.test.tsx
- packages/module/src/ChatbotHeader/ChatbotHeaderActions.test.tsx
- packages/module/src/ChatbotHeader/ChatbotHeaderCloseButton.test.tsx
- packages/module/src/ChatbotHeader/ChatbotHeaderMain.test.tsx
- packages/module/src/ChatbotHeader/ChatbotHeaderMenu.test.tsx
- packages/module/src/ChatbotHeader/ChatbotHeaderOptionsDropdown.test.tsx
- packages/module/src/ChatbotHeader/ChatbotHeaderSelectorDropdown.test.tsx
- packages/module/src/ChatbotHeader/ChatbotHeaderTitle.test.tsx
- packages/module/src/MessageBar/MessageBar.test.tsx
- packages/module/src/MessageBox/MessageBox.test.tsx
- packages/module/src/PreviewAttachment/PreviewAttachment.test.tsx
- packages/module/src/Settings/SettingsForm.test.tsx
Increase unit test coverage. - https://github.com/patternfly/chatbot/issues/255
**Before:**
**After:**
> fix(tests): increase unit test coverage

- packages/module/src/MessageBar/MessageBar.test.tsx
- packages/module/src/MessageBar/MessageBar.tsx
Can now use value prop to provide default value.
> feat(MessageBar): Allow for controlled input

- package-lock.json
- package.json
- packages/module/package.json
- packages/module/patternfly-docs/content/extensions/chatbot/examples/Analytics/Analytics.md
Analytics PR re-introduced dompurify; we don't need this anymore. Missed it at the time.
> chore(docs): Drop dompurify dep again

- packages/module/src/Message/UserFeedback/UserFeedback.test.tsx
- packages/module/src/Message/UserFeedback/UserFeedback.tsx
Design wants to drop cancel button - deprecating prop and removing it from the component.
> fix(UserFeedback): Remove cancel button

- packages/module/patternfly-docs/content/extensions/chatbot/examples/demos/Chatbot.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/demos/ChatbotAttachment.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/demos/ChatbotAttachmentMenu.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/demos/ChatbotInDrawer.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/demos/EmbeddedChatbot.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/demos/EmbeddedComparisonChatbot.tsx
- packages/module/patternfly-docs/content/extensions/chatbot/examples/demos/Feedback.tsx
> chore(demos): added style imports to demos

- packages/module/patternfly-docs/content/extensions/chatbot/examples/Messages/MessageWithFeedback.tsx
- packages/module/src/Message/Message.test.tsx
- packages/module/src/Message/Message.tsx
- packages/module/src/Message/QuickResponse/QuickResponse.tsx
- packages/module/src/Message/UserFeedback/UserFeedback.scss
- packages/module/src/Message/UserFeedback/UserFeedback.test.tsx
- packages/module/src/Message/UserFeedback/UserFeedback.tsx
- packages/module/src/Message/UserFeedback/UserFeedbackComplete.test.tsx
- packages/module/src/Message/UserFeedback/UserFeedbackComplete.tsx
I'm breaking the density ticket into a series of smaller tickets so they'll be easier to review. This is only the spacing changes for the feedback card - font, etc. will be adjusted in a separate PR.
Docs: https://chatbot-pr-chatbot-520.surge.sh/patternfly-ai/chatbot/messages#message-feedback
> feat(UserFeedback): Add compact versions

- packages/module/src/MessageBox/MessageBox.tsx
Added ...props spread operator to MessageBox so you can add ids, etc.
> fix(MessageBox): Allow passing additional props

- packages/module/src/MessageBox/MessageBox.test.tsx
- packages/module/src/MessageBox/MessageBox.tsx
Expose onClick handlers so developers can further customize scroll behavior.
> fix(JumpLinks): Add onClick handlers

- packages/module/src/ChatbotHeader/ChatbotHeader.scss
Design asked for us to go from sm to md padding.
https://chatbot-pr-chatbot-594.surge.sh/patternfly-ai/chatbot/overview/demo/compact-chatbot/
> fix(ChatbotHeader): Adjust compact variant padding

- packages/module/patternfly-docs/content/extensions/chatbot/examples/demos/Chatbot.md
> docs(chatbot): Edit docs for inline drawer demo.
